select 
	CD_ATENDIMENTO
	,CD_ORI_ATE
	,CD_CONVENIO
	,CD_PRO_INT
	,CD_PRO_INT_PROCEDIMENTO_ENTRAD
	,TO_CHAR(DT_ATENDIMENTO, 'YYYY-MM-DD hh24:mi:ss') as DT_ATENDIMENTO
	,TO_CHAR(HR_ATENDIMENTO, 'YYYY-MM-DD hh24:mi:ss') as HR_ATENDIMENTO
	,NULLIF(REGEXP_REPLACE(TP_ATENDIMENTO,'[''"!/:@;]', ''),'') as TP_ATENDIMENTO
	,CD_SERVICO
	,TO_CHAR(DT_ALTA, 'YYYY-MM-DD hh24:mi:ss') as DT_ALTA
	,TO_CHAR(DT_ENTRADA_SAME, 'YYYY-MM-DD hh24:mi:ss') as DT_ENTRADA_SAME
	,TO_CHAR(DT_PREVISTA_ALTA, 'YYYY-MM-DD hh24:mi:ss') as DT_PREVISTA_ALTA
	,TO_CHAR(HR_ALTA, 'YYYY-MM-DD hh24:mi:ss') as HR_ALTA
	,CD_CON_PLA
	,CD_CONVENIO_SECUNDARIO
	,CD_CON_PLA_SECUNDARIO
	,CD_MULTI_EMPRESA
	,CD_ATENDIMENTO_PAI
	,CD_TIP_SITUACAO
	,NULLIF(REGEXP_REPLACE(TP_PRIORIDADE,'[''"!/:@;]', ''),'')  as TP_PRIORIDADE
	,CD_SSM_SIA
	,CD_GRU_ATE
	,NULLIF(REGEXP_REPLACE(SN_CONSULTA_SIASUS,'[''"!/:@;]', ''),'')  as SN_CONSULTA_SIASUS
	,TO_CHAR(DT_VALIDADE, 'YYYY-MM-DD hh24:mi:ss') as DT_VALIDADE
	,CD_ATENDIMENTO_SUS_VINCULADO
	,NULLIF(REGEXP_REPLACE(TP_ATENDIMENTO_TISS,'[''"!/:@;]', ''),'')  as TP_ATENDIMENTO_TISS
	,CD_PROCEDIMENTO
	,CD_ATENDIMENTO_ORIGINAL
from atendime
where 
	dt_atendimento >= ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
																then '-5' 
																ELSE '-4'
															END ))
	AND dt_atendimento < ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
																	then '-1' 
																	ELSE '0'
																END ))	