SELECT 
 IE.CD_ITLOT_ENT	
 ,IE.CD_ITENT_PRO
 ,NULLIF(REGEXP_REPLACE(IE.CD_LOTE,'[''"!/:@;]', ''),'') as CD_LOTE
 ,TO_CHAR(IE.DT_VALIDADE, 'YYYY-MM-DD hh24:mi:ss') as DT_VALIDADE
 ,IE.QT_ENT_PRO
 ,IE.QT_DEVOLVIDO
 ,NULLIF(REGEXP_REPLACE(IE.DS_MARCA,'[''"!/:@;]', ''),'') as DS_MARCA
 ,IE.CD_UNI_PRO
 ,TO_CHAR(IE.DT_GRAVACAO, 'YYYY-MM-DD hh24:mi:ss') as DT_GRAVACAO
 ,NULLIF(REGEXP_REPLACE(IE.CD_SEQ_INTEGRA,'[''"!/:@;]', ''),'') as CD_SEQ_INTEGRA
 ,TO_CHAR(IE.DT_INTEGRA, 'YYYY-MM-DD hh24:mi:ss') as DT_INTEGRA
FROM
	DBAMV.ITLOT_ENT IE