SELECT
 l.CD_LOTE
 ,NULLIF(REGEXP_REPLACE(l.DS_LOTE,'[''"!/:@;]', ''),'') as DS_LOTE
 ,TO_CHAR(l.DT_INICIAL_LCTO, 'YYYY-MM-DD hh24:mi:ss') as DT_INICIAL_LCTO
 ,TO_CHAR(l.DT_FINAL_LCTO, 'YYYY-MM-DD hh24:mi:ss') as DT_FINAL_LCTO
 ,l.VL_LOTE
 ,TO_CHAR(l.DT_LIBERADO, 'YYYY-MM-DD hh24:mi:ss') as DT_LIBERADO
 ,l.CD_MULTI_EMPRESA
 ,TO_CHAR(l.DT_CRIACAO, 'YYYY-MM-DD hh24:mi:ss') as DT_CRIACAO
 ,l.CD_MULTI_EMPRESA_ORIGEM
 ,l.CD_LOTE_PAI
 ,NULLIF(REGEXP_REPLACE(l.SN_LOTE_APURACAO_RESULTADO,'[''"!/:@;]', ''),'') as SN_LOTE_APURACAO_RESULTADO
 ,NULLIF(REGEXP_REPLACE(l.CD_LOTE_INTEGRA,'[''"!/:@;]', ''),'') as CD_LOTE_INTEGRA
 ,TO_CHAR(l.DT_INTEGRA, 'YYYY-MM-DD hh24:mi:ss') as DT_INTEGRA
 ,l.CD_SEQ_INTEGRA
 ,NULLIF(REGEXP_REPLACE(l.SN_IMPORTADO,'[''"!/:@;]', ''),'') as SN_IMPORTADO
 ,NULLIF(REGEXP_REPLACE(l.TP_LANCAMENTO,'[''"!/:@;]', ''),'') as TP_LANCAMENTO
 ,l.CD_LOTE_EXT
 ,l.CD_LCTO_MOV_EXT
 ,TO_CHAR(l.DT_LCTO_EXT, 'YYYY-MM-DD hh24:mi:ss') as DT_LCTO_EXT
FROM
	DBAMV.LOTE L;
