SELECT
	 CD_SETOR
	 ,NULLIF(REGEXP_REPLACE(NM_SETOR,'[''"!/:@;]', ''),'') as NM_SETOR 	
	 ,NULLIF(REGEXP_REPLACE(CD_CEN_CUS,'[''"!/:@;]', ''),'') as CD_CEN_CUS 	
	 ,NULLIF(REGEXP_REPLACE(SN_PODE_SOLICITAR_EXAMES,'[''"!/:@;]', ''),'') as SN_PODE_SOLICITAR_EXAMES 	
	 ,CD_FATOR
	 ,CD_GRUPO_DE_CUSTO
	 ,CD_SETOR_CUSTO
	 ,NR_ORDEM_RATEIO
	 ,NULLIF(REGEXP_REPLACE(SN_CENTRO_DE_CUSTO,'[''"!/:@;]', ''),'') as SN_CENTRO_DE_CUSTO 	
	 ,NULLIF(REGEXP_REPLACE(CLASSIFICACAO,'[''"!/:@;]', ''),'') as CLASSIFICACAO 	
	 ,CD_MULTI_EMPRESA
	 ,NULLIF(REGEXP_REPLACE(TP_RAT_MAT_DIRETOS,'[''"!/:@;]', ''),'') as TP_RAT_MAT_DIRETOS 	
	 ,NULLIF(REGEXP_REPLACE(SN_ACEITA_LANCAMENTO,'[''"!/:@;]', ''),'') as SN_ACEITA_LANCAMENTO 	
	 ,NULLIF(REGEXP_REPLACE(CD_ROTINA,'[''"!/:@;]', ''),'') as CD_ROTINA 	
	 ,NULLIF(REGEXP_REPLACE(SN_PRODUCAO_FATURADA,'[''"!/:@;]', ''),'') as SN_PRODUCAO_FATURADA 	
	 ,NULLIF(REGEXP_REPLACE(SN_CALCULO_EVENTO,'[''"!/:@;]', ''),'') as SN_CALCULO_EVENTO 	
	 ,NULLIF(REGEXP_REPLACE(TP_COMPOSICAO_CALCULO,'[''"!/:@;]', ''),'') as TP_COMPOSICAO_CALCULO 	
	 ,NULLIF(REGEXP_REPLACE(CD_ROTINA_MAT_DIRETOS,'[''"!/:@;]', ''),'') as CD_ROTINA_MAT_DIRETOS 	
	 ,CD_SEQ_RESUMO
	 ,CD_SEQ_DETALHE
	 ,NULLIF(REGEXP_REPLACE(SN_DEDUCAO_HONORARIO,'[''"!/:@;]', ''),'') as SN_DEDUCAO_HONORARIO 	
	 ,NULLIF(REGEXP_REPLACE(SN_EXPORTA_FFIS,'[''"!/:@;]', ''),'') as SN_EXPORTA_FFIS 	
	 ,NULLIF(REGEXP_REPLACE(SN_ATIVO,'[''"!/:@;]', ''),'') as SN_ATIVO 	
	 ,NULLIF(REGEXP_REPLACE(DS_CAMINHO_IMPRESSORA,'[''"!/:@;]', ''),'') as DS_CAMINHO_IMPRESSORA 	
	 ,CD_SETOR_EXPORTACAO
	 ,NULLIF(REGEXP_REPLACE(TP_CALCULO_HONORARIO,'[''"!/:@;]', ''),'') as TP_CALCULO_HONORARIO 	
	 ,NULLIF(REGEXP_REPLACE(SN_IMPRIME_LAUDO_LOCAL,'[''"!/:@;]', ''),'') as SN_IMPRIME_LAUDO_LOCAL 	
	 ,NULLIF(REGEXP_REPLACE(DS_IMPRESSORA_ETIQ_COLETA,'[''"!/:@;]', ''),'') as DS_IMPRESSORA_ETIQ_COLETA 	
	 ,NULLIF(REGEXP_REPLACE(TP_SETOR,'[''"!/:@;]', ''),'') as TP_SETOR 	
	 ,CD_MULTI_EMPRESA_ORIGEM
	 ,NULLIF(REGEXP_REPLACE(SN_VER_EXAME_N_LIBERADO,'[''"!/:@;]', ''),'') as SN_VER_EXAME_N_LIBERADO 	
	 ,NULLIF(REGEXP_REPLACE(CD_SETOR_INTEGRA,'[''"!/:@;]', ''),'') as CD_SETOR_INTEGRA 	
	 ,NULLIF(REGEXP_REPLACE(DS_SIGLA_AGENDAMENTO,'[''"!/:@;]', ''),'') as DS_SIGLA_AGENDAMENTO 
	 ,NULLIF(REGEXP_REPLACE(TP_GRUPO_SETOR,'[''"!/:@;]', ''),'') as TP_GRUPO_SETOR 
	 ,CD_PRESTADOR_RESPONSAVEL
	 ,NULLIF(REGEXP_REPLACE(SN_VER_EXAME_IMG_N_LIB,'[''"!/:@;]', ''),'') as SN_VER_EXAME_IMG_N_LIB 
	
 FROM
 	DBAMV.SETOR
