version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3793:3793"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      PATH: "/opt/oracle/instantclient:$PATH"
      TNS_ADMIN: /opt/oracle/instantclient
    restart: always
