SELECT
    CD_CLASSE_MATERIAL      
	, NULLIF(REGEXP_REPLACE(DS_CLASSE_MATERIAL,'[''"!/:@;]', ''),'') AS DS_CLASSE_MATERIAL       
    , CD_SUBGRUPO_MATERIAL
    , IE_SITUACAO
    ,TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
FROM
    TASY.CLASSE_MATERIAL