SELECT 
	NR_ATENDIMENTO
	,TO_CHAR(DT_ACERTO_CONTA,'YYYY-MM-DD hh24:mi:ss') AS DT_ACERTO_CONTA
	,IE_STATUS_ACERTO
	,TO_CHAR(DT_PERIODO_INICIAL, 'YYYY-MM-DD hh24:mi:ss') AS DT_PERIODO_INICIAL
	,TO_CHAR(DT_PERIODO_FINAL, 'YYYY-MM-DD hh24:mi:ss') AS DT_PERIODO_FINAL
	,TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	,TO_CHAR(DT_MESANO_REFERENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_MESANO_REFERENCIA
	,NR_INTERNO_CONTA
	,TO_CHAR(DT_RECALCULO, 'YYYY-MM-DD hh24:mi:ss') AS DT_RECALCULO
	,CD_ESTABELECIMENTO
	,IE_CANCELAMENTO
	,to_char(VL_CONTA) AS VL_CONTA
	,to_char(VL_DESCONTO) AS VL_DESCONTO
	,TO_CHAR(DT_CANCELAMENTO, 'YYYY-MM-DD hh24:mi:ss') AS DT_CANCELAMENTO
	,CD_PROC_PRINC
	,TO_CHAR(DT_CONTA_DEFINITIVA, 'YYYY-MM-DD hh24:mi:ss') AS DT_CONTA_DEFINITIVA
	,IE_TIPO_ATEND_CONTA
FROM
	TASY.CONTA_PACIENTE cp	
WHERE
	cp.NR_INTERNO_CONTA IN (
	SELECT
		NR_INTERNO_CONTA
	FROM
		TASY.MATERIAL_ATEND_PACIENTE map2
	WHERE
		map2.dt_atendimento >= ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
											then '-5' 
											ELSE '-4'
										END ))
		AND map2.dt_atendimento < ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
											then '-1' 
											ELSE '0'
										END ))	
		)