SELECT 
	NR_SEQUENCIA
	, CD_CONVENIO
	, CD_MATERIAL_CONVENIO
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	, CD_GRUPO_MATERIAL
	, CD_SUBGRUPO_MATERIAL
	, CD_CLASSE_MATERIAL
	, CD_MATERIAL
    , NULLIF(REGEXP_REPLACE(DS_MATERIAL_CONVENIO,'[''"!/:@;]', ''),'') AS DS_MATERIAL_CONVENIO  
	, CD_GRUPO
	, TX_CONVERSAO_QTDE
	, CD_UNIDADE_CONVENIO
    , TO_CHAR(DT_INICIO_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_INICIO_VIGENCIA
    , TO_CHAR(DT_FINAL_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_FINAL_VIGENCIA
	, CD_ESTABELECIMENTO
	, IE_SITUACAO
	, IE_ORIGEM_PRECO
	, IE_PACOTE
	, IE_TIPO_MATERIAL 
FROM 
	TASY.CONVERSAO_MATERIAL_CONVENIO