SELECT 
	CD_ESTABELECIMENTO
	, IE_SITUACAO
	, CD_CGC
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	, CD_EMPRESA
	, IE_CONVENIADO_SUS
	, PR_ICMS_ESTADO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
    , NULLIF(REGEXP_REPLACE(NM_FANTASIA_ESTAB,'[''"!/:@;]', ''),'') AS NM_FANTASIA_ESTAB 
	, IE_RAZAO_FANTASIA
    , NULLIF(REGEXP_REPLACE(NM_SIGLA_ESTAB,'[''"!/:@;]', ''),'') AS NM_SIGLA_ESTAB 
	, IE_NOME_SOCIAL
	, IE_TIPO_ESTAB 
FROM 
	TASY.ESTABELECIMENTO