SELECT 
	CD_GRUPO_MATERIAL
    , NULLIF(REGEXP_REPLACE(DS_GRUPO_MATERIAL,'[''"!/:@;]', ''),'') AS DS_GRUPO_MATERIAL 
	, IE_SITUACAO
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
FROM 
	TASY.GRUPO_MATERIAL