SELECT 
	NR_SEQUENCIA
    , NULLIF(REGEXP_REPLACE(DS_FABRICANTE,'[''"!/:@;]', ''),'') AS DS_FABRICANTE 
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
FROM 
	TASY.MAT_FABRICANTE