 SELECT
     CD_MATERIAL,
     CD_UNIDADE_MEDIDA,
     to_char(QT_CONVERSAO) as QT_CONVERSAO,
     IE_PRIORIDADE,
     NM_USUARIO,
     TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO,
     TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC,
     NM_USUARIO_NREC,
     IE_PERMITE_PRESCR,
     to_char(QT_DIVISOR_MINIMO) as QT_DIVISOR_MINIMO
 FROM
    TASY.MATERIAL_CONVERSAO_UNIDADE
