SELECT
    NR_SEQUENCIA
    ,CD_ESTABELECIMENTO
    ,TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    ,REGEXP_REPLACE(NM_USUARIO,'[''"!/:@;]', '') as NM_USUARIO
    ,IE_REGRA_DISP
    ,CD_MATERIAL
    ,CD_CONVENIO
    ,CD_SETOR_ATENDIMENTO
    ,TO_CHAR(dt_atualizacao_nrec, 'YYYY-MM-DD hh24:mi:ss') as DT_ATUALIZACAO_NREC
    ,REGEXP_REPLACE(NM_USUARIO_NREC,'[''"!/:@;]', '') as NM_USUARIO_NREC
    ,QT_LIMITE
    ,QT_LIMITE_MAX
    ,CD_KIT_MATERIAL
    ,CD_CATEGORIA
    ,NR_MULTIPLO
    ,TO_CHAR(DT_INICIO_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_INICIO_VIGENCIA
    ,TO_CHAR(DT_FINAL_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_FINAL_VIGENCIA
    ,IE_TIPO_DATA
    ,CD_GRUPO_MATERIAL
    ,CD_SUBGRUPO_MATERIAL
    ,CD_CLASSE_MATERIAL
    ,CD_PERFIL
    ,CD_FUNCAO
FROM
    TASY.MATERIAL_REGRA_QT_FAT
