SELECT
	NR_SEQUENCIA
	, NR_ATENDIMENTO
	, CD_MATERIAL
    , TO_CHAR(DT_ATENDIMENTO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATENDIMENTO
	, CD_UNIDADE_MEDIDA
	, to_char(QT_MATERIAL) AS QT_MATERIAL
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	, CD_CONVENIO
	, CD_CATEGORIA
	, CD_MATERIAL_PRESCRICAO
	, to_char(VL_MATERIAL) AS VL_MATERIAL
	, CD_TAB_PRECO_MATERIAL
    , TO_CHAR(DT_ACERTO_CONTA, 'YYYY-MM-DD hh24:mi:ss') AS DT_ACERTO_CONTA
    , TO_CHAR(DT_ACERTO_CONVENIO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ACERTO_CONVENIO
	, NR_DOC_CONVENIO
	, to_char(QT_EXECUTADA) AS QT_EXECUTADA
    , TO_CHAR(DT_CONTA, 'YYYY-MM-DD hh24:mi:ss') AS DT_CONTA
	, to_char(VL_UNITARIO) AS VL_UNITARIO
	, IE_VALOR_INFORMADO
	, CD_ESTABELECIMENTO_CUSTO
	, CD_TABELA_CUSTO
	, CD_SITUACAO_GLOSA
	, CD_MATERIAL_CONVENIO
	, NR_INTERNO_CONTA
	, NR_SEQ_PROC_PACOTE
	, to_char(VL_TABELA_ORIGINAL) AS VL_TABELA_ORIGINAL
	, CD_MATERIAL_EXEC
	, IE_AUDITORIA
	, NR_SEQ_CONTA_ORIGEM
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, IE_ORIGEM_PRECO
	, to_char(QT_ESTOQUE) AS QT_ESTOQUE
	, NR_SEQ_TISS_TABELA
	, CD_MATERIAL_TISS
    , NULLIF(REGEXP_REPLACE(DS_MATERIAL_TISS,'[''"!/:@;]', ''),'') AS DS_MATERIAL_TISS 
	, CD_TAB_CUSTO_PRECO
	, NR_SEQ_MAT_GLOSA
	, CD_LABORATORIO
	, CD_MEDICAMENTO
	, CD_APRESENTACAO
	, to_char(VL_MATERIAL_TISS) AS VL_MATERIAL_TISS
	, CD_CENTRO_CUSTO_RECEITA
	, CD_SIMPRO
	, IE_RATEAR_ITEM
	, NR_SEQ_BRAS_PRECO
	, NR_SEQ_CONV_BRAS
	, NR_SEQ_MAT_BRAS
	, CD_MATERIAL_TUSS
	, NR_SEQ_TUSS_MAT_ITEM
	, NR_REGISTRO_ANVISA_TISS
	, IE_OPME
	, NR_SEQ_MAT_SIMP
	, NR_SEQ_CONV_SIMP
	, NR_SEQ_SIMP_PRECO
    , NULLIF(REGEXP_REPLACE(DS_MATERIAL_TUSS,'[''"!/:@;]', ''),'') AS DS_MATERIAL_TUSS 
	, CD_UNID_MEDIDA_CONV
	, to_char(TX_CONVERSAO_QTDE) AS TX_CONVERSAO_QTDE
FROM
	TASY.MATERIAL_ATEND_PACIENTE	
WHERE
	dt_atendimento >= ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
																then '-5' 
																ELSE '-4'
															END ))
	AND dt_atendimento < ADD_MONTHS(TRUNC(SYSDATE, 'mm'), (CASE WHEN EXTRACT(DAY FROM sysdate) < 20 
																	then '-1' 
																	ELSE '0'
																END ))	
