SELECT 
	NR_SEQUENCIA
	, CD_MATERIAL
	, CD_SIMPRO
	, TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , to_char(QT_CONVERSAO) AS QT_CONVERSAO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, CD_ESTABELECIMENTO
	, CD_CONVENIO
    , TO_CHAR(DT_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_VIGENCIA
	, IE_SITUACAO
    , TO_CHAR(DT_FINAL_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_FINAL_VIGENCIA
	, IE_TIPO_CONVENIO
FROM 
	TASY.MATERIAL_SIMPRO