SELECT 
	CD_MATERIAL
    , NULLIF(REGEXP_REPLACE(DS_MATERIAL,'[''"!/:@;]', ''),'') AS DS_MATERIAL 
    , NULLIF(REGEXP_REPLACE(DS_REDUZIDA,'[''"!/:@;]', ''),'') AS DS_REDUZIDA 
	, CD_CLASSE_MATERIAL
	, CD_UNIDADE_MEDIDA_COMPRA
	, CD_UNIDADE_MEDIDA_ESTOQUE
	, CD_UNIDADE_MEDIDA_CONSUMO
	, IE_MATERIAL_ESTOQUE
	, IE_SITUACAO
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	, IE_VIA_APLICACAO
    , to_char(QT_CONV_COMPRA_ESTOQUE) AS QT_CONV_COMPRA_ESTOQUE
	, CD_UNIDADE_MEDIDA_SOLIC
    , to_char(QT_CONVERSAO_MG) AS QT_CONVERSAO_MG
	, IE_TIPO_MATERIAL
	, CD_MATERIAL_GENERICO
    , to_char(QT_CONV_ESTOQUE_CONSUMO) AS QT_CONV_ESTOQUE_CONSUMO
	, CD_MATERIAL_ESTOQUE
	, CD_MATERIAL_CONTA
	, IE_CONSIGNADO
	, IE_UTILIZACAO_SUS
	, CD_UNID_MED_LIMITE
	, CD_MEDICAMENTO
	, CD_FABRICANTE
	, NR_SEQ_FABRIC
	, IE_SOLUCAO
	, CD_UNID_MED_CONCETRACAO
    , NULLIF(REGEXP_REPLACE(DS_MATERIAL_SEM_ACENTO,'[''"!/:@;]', ''),'') AS DS_MATERIAL_SEM_ACENTO 
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
    , to_char(QT_CONV_COMPRA_EST) AS QT_CONV_COMPRA_EST
	, CD_UNID_MEDIDA
	, NR_REGISTRO_ANVISA
    , TO_CHAR(DT_VALIDADE_REG_ANVISA, 'YYYY-MM-DD hh24:mi:ss') AS DT_VALIDADE_REG_ANVISA
	, CD_MATERIAL_SUBS
	, IE_PERMITE_FRACIONADO
	, NR_SEQ_FICHA_TECNICA
FROM 
    TASY.MATERIAL