SELECT 
	CD_LABORATORIO
	, CD_MEDICAMENTO
	, CD_APRESENTACAO
	, CD_MATERIAL
	, IE_PRIORIDADE
	, IE_SITUACAO
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , to_char(QT_CONVERSAO) AS QT_CONVERSAO
    , TO_CHAR(DT_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_VIGENCIA
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, CD_CONVENIO
	, NR_SEQUENCIA
	, CD_ESTABELECIMENTO
	, IE_TIPO_CONVENIO
    , TO_CHAR(DT_FINAL_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_FINAL_VIGENCIA
FROM TASY.MATERIAL_BRASINDICE