SELECT 
	NR_SEQUENCIA
	, CD_MATERIAL
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, CD_CONVENIO
	, CD_CATEGORIA
	, IE_TIPO_ATENDIMENTO
    , TO_CHAR(DT_VIGENCIA_INICIAL, 'YYYY-MM-DD hh24:mi:ss') AS DT_VIGENCIA_INICIAL
    , TO_CHAR(DT_VIGENCIA_FINAL, 'YYYY-MM-DD hh24:mi:ss') AS DT_VIGENCIA_FINAL
	, IE_ORIGEM_PRECO
	, NR_SEQ_TUSS_MAT
	, NR_SEQ_TUSS_MAT_ITEM
	, CD_MATERIAL_TUSS
	, IE_SITUACAO
	, CD_ESTABELECIMENTO
	, NR_SEQ_MARCA
	, CD_CGC_FORNECEDOR 
FROM 
	TASY.MATERIAL_TUSS