SELECT NR_SEQUENCIA
    ,TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    ,NULLIF(REGEXP_REPLACE(DS_SUBSTANCIA,'[''"!/:@;]', ''),'') AS DS_SUBSTANCIA
    ,NULLIF(REGEXP_REPLACE(DS_SINONIMO,'[''"!/:@;]', ''),'') AS DS_SINONIMO
    ,NR_SEQ_DCI
    ,NR_SEQ_DCB
    ,TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
    ,IE_ANTIMICROBIANO
    ,NR_SEQ_SUPERIOR
    ,IE_MARGEM_TERAP_ESTREITA
    ,NR_EXTERNO
    ,IE_SE_GESTANTE
    ,IE_SITUACAO
FROM TASY.MEDIC_FICHA_TECNICA
