SELECT 
	CD_NATUREZA_OPERACAO
    , NULLIF(REGEXP_REPLACE(DS_NATUREZA_OPERACAO,'[''"!/:@;]', ''),'') AS DS_NATUREZA_OPERACAO 
	, IE_ENTRADA_SAIDA
	, IE_SITUACAO
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, CD_CODIGO_INTERNO
	, IE_TIPO_NATUREZA
FROM 
	TASY.NATUREZA_OPERACAO