
SELECT 
	NR_SEQUENCIA
	, CD_ESTABELECIMENTO
	, CD_SERIE_NF
	, NR_SEQUENCIA_NF
	, NR_ITEM_NF
	, CD_NATUREZA_OPERACAO
    , TO_CHAR(QT_ITEM_NF) AS QT_ITEM_NF
    , TO_CHAR(VL_UNITARIO_ITEM_NF) AS VL_UNITARIO_ITEM_NF
    , TO_CHAR(VL_TOTAL_ITEM_NF) AS VL_TOTAL_ITEM_NF
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , TO_CHAR(VL_DESCONTO) AS VL_DESCONTO
	, CD_MATERIAL
	, CD_PROCEDIMENTO
	, CD_CONTA
	, CD_LOCAL_ESTOQUE
	, CD_UNIDADE_MEDIDA_COMPRA
    , TO_CHAR(QT_ITEM_ESTOQUE) AS QT_ITEM_ESTOQUE
    , CD_UNIDADE_MEDIDA_ESTOQUE
    , TO_CHAR(VL_DESCONTO_RATEIO) AS VL_DESCONTO_RATEIO
	, CD_MATERIAL_ESTOQUE
	, NR_ATENDIMENTO
	, NR_NOTA_FISCAL
	, NR_SEQ_MARCA
	, IE_MATERIAL_ESTOQUE
	, CD_LOTE_FABRICACAO 
	, NR_SEQ_LOTE_FORNEC
	, TO_CHAR(DT_VALIDADE, 'YYYY-MM-DD hh24:mi:ss') AS DT_VALIDADE
FROM 
	TASY.NOTA_FISCAL_ITEM nfi 	
WHERE
	DT_ATUALIZACAO >= TO_DATE('2019-01-01','yyyy-mm-dd')
