SELECT 
	NR_SEQUENCIA
	, CD_ESTABELECIMENTO
	, IE_TIPO_RECEBIMENTO
	, CD_SERIE_NF
	, NR_NOTA_FISCAL
	, NR_SEQUENCIA_NF
	, CD_OPERACAO_NF
    , TO_CHAR(DT_EMISSAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_EMISSAO
    , TO_CHAR(DT_ENTRADA_SAIDA, 'YYYY-MM-DD hh24:mi:ss') AS DT_ENTRADA_SAIDA
	, IE_ACAO_NF
	, IE_EMISSAO_NF
	, IE_TIPO_FRETE
    , to_char(VL_TOTAL_NOTA) AS VL_TOTAL_NOTA
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , to_char(VL_IPI) AS VL_IPI
    , to_char(VL_DESCONTOS) AS VL_DESCONTOS
	, NR_NOTA_REFERENCIA
	, CD_SERIE_REFERENCIA
	, CD_NATUREZA_OPERACAO
    , TO_CHAR(DT_ATUALIZACAO_ESTOQUE, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_ESTOQUE
    , TO_CHAR(VL_DESCONTO_RATEIO) AS VL_DESCONTO_RATEIO
    , IE_SITUACAO
	, NR_ORDEM_COMPRA
	, NR_SEQUENCIA_REF
	, NR_INTERNO_CONTA
	, IE_TIPO_NOTA
	, IE_STATUS_ENVIO
	, NR_SEQ_MOTIVO_CANCEL
	, NR_SEQ_MOTIVO_DEVOL
	, NR_DANFE
    , TO_CHAR(DT_ATUALIZACAO_NREC, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO_NREC
	, IE_STATUS_NFE
    , NULLIF(REGEXP_REPLACE(DS_MARCA,'[''"!/:@;]', ''),'') AS DS_MARCA
    , TO_CHAR(DT_CANCELAMENTO_NFE, 'YYYY-MM-DD hh24:mi:ss') AS DT_CANCELAMENTO_NFE
    , TO_CHAR(DT_EMISSAO_NFE, 'YYYY-MM-DD hh24:mi:ss') AS DT_EMISSAO_NFE
	, NR_SEQ_NF_REF
	, NR_SEQ_FATURA
	, NR_SEQ_FORMA_PAGTO
    , TO_CHAR(DT_APROVACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_APROVACAO
    , TO_CHAR(DT_CANCELAMENTO, 'YYYY-MM-DD hh24:mi:ss') AS DT_CANCELAMENTO
	, nr_seq_lote_res_pls 
	, nr_seq_lote_prot 
	, nr_seq_nf_lote_nfe 
	, nr_lote_contabil 
	, cd_cgc_emitente
FROM 
	TASY.NOTA_FISCAL	
WHERE 
	DT_ATUALIZACAO >= to_date('2019-01-01','yyyy-mm-dd')	
