SELECT cd_estabelecimento
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') as dt_atualizacao
    , ie_repasse_mat
    , ie_repasse_proc
    , cd_motivo_exc_conta
    , ie_exige_lib_bras
    , nr_seq_terceiro
    , ie_nf_guia_partic
    , ie_pre_faturamento
    , ie_diaria_apos_vig
    , ie_historico_conta
    , ie_conta_repasse
    , pr_perm_prej_pacote
    , ie_titulo_nf_saida
    , TO_CHAR(dt_mesano_referencia, 'YYYY-MM-DD') as dt_mesano_referencia
    , ie_audita_retorno
    , cd_convenio_partic
    , cd_categoria_partic
    , ie_item_zerado_conta
    , ie_fechar_conta_ps_alta
    , ie_transfere_unidade_cir
    , ie_setor_receita
    , ie_canc_proc_prescr
    , ie_atualiza_taxa_adm
    , ie_consiste_tipo_conv
    , cd_funcao_medico
    , ie_nf_contab_rec
    , ie_fora_linha_simpro
    , ie_codigo_barra_conta
    , ie_forma_especialidade
    , ie_adicional_retorno
    , to_char(qt_ano_min_acomp) AS qt_ano_min_acomp
    , to_char(qt_ano_max_acomp) AS qt_ano_max_acomp
    , ie_lote_ctb_trib_nf
    , ie_consiste_partic_menor
    , ie_repasse_amenor_audit
    , ie_gerar_resp_credito
    , ie_tipo_protocolo
    , ie_prot_ctb_rec
    , TO_CHAR(dt_atualizacao_nrec, 'YYYY-MM-DD hh24:mi:ss') as dt_atualizacao_nrec
    , ie_titulo_ctb_receita
    , ie_especial_proc_exec
    , ie_trib_venc_repasse
    , ie_tipo_protocolo_bpa
    , ie_estabelecimento_conta
    , ie_preco_inf_glosa_proc
    , ie_tipo_protocolo_aih
    , ie_intervalo_prescr
    , ie_gerar_conta_guia_dif
    , ie_repasse_estorno
    , ie_prioridade_edicao_amb
    , ie_prioridade_ajuste_proc
    , ie_repasse_gratuidade
    , nr_seq_estagio_autor
    , ie_calcula_nf
    , ie_cancelar_autor_prescr
    , ie_cancelar_dif_diaria
    , ie_atualiza_cgc_partic
    , ie_gerar_pacote_canc_nota
    , ie_calculo_taxa_regra
    , ie_permite_matmed_inativo
    , ie_gera_proc_princ_cih
    , cd_convenio_sus
    , ie_nf_contab_rec_conv
    , ie_altera_medico_proc_cta
    , ie_data_lib_repasse_ret
    , ie_atualiza_func_medico
    , ie_gerar_taxa_sala_insert
    , ie_calcular_mat_auditado
    , ie_conv_calculo_honorario
    , ie_regra_honorario_servico
    , ie_retorno_neg
    , ie_gerar_mat_assoc_lib_prescr
    , ie_excluir_rep_zerado
    , ie_contab_repasse_receita
    , ie_estab_regra_honorario
    , ie_cobra_kit_prescr
    , ie_data_vig_cbhpm
    , ie_contab_repasse_prefatur
    , TO_CHAR(dt_competencia_sus, 'YYYY-MM-DD hh24:mi:ss') as dt_competencia_sus
    , ie_gerar_instrumentador
    , ie_repasse_cheque_comp
    , ie_valor_inf_desconto
    , ie_exclui_partic_cir_zerado
    , ie_dt_contab_tit_prot
    , ie_glosa_mat_proc_princ
    , ie_aux_cbhpm_porte_cir
    , ie_aux_amb_porte_cir
    , ie_estab_pre_faturamento
    , ie_consiste_autor_exec
    , ie_fechar_conta_alta
    , ie_gerar_diaria_futura
    , ie_manter_pacote_zerado
    , ie_valor_inf_pacote
    , ie_centro_custo_inativo
    , ie_calc_partic_ipsemg
    , ie_regra_auxiliar_ipe
    , ie_dispara_regra_lanc_kit
    , ie_consiste_anest_porte
    , TO_CHAR(dt_comp_apac_bpa, 'YYYY-MM-DD hh24:mi:ss') as dt_comp_apac_bpa
    , ie_proc_sus_antigo
    , ie_convenio_conta_param
    , ie_vigencia_aux_cbhpm
    , ie_lanc_auto_sus_alta
    , ie_agrupa_data_ipe
    , ie_lib_materiais_esp
    , ie_edicao_ajuste_partic_cir
    , ie_repasse_zerado
    , ie_converte_proc_conv
    , ie_dia_util_autor
    , nr_seq_trans_troca_terc
    , ie_lib_presc_autor_medico
    , ie_regra_conta_terc_mat
    , ie_atualizar_tipo_conv_atend
    , ie_autor_compl_agenda
    , ie_dividir_indice_pmc
    , ie_dividir_indice_pfb
    , ie_contab_cc_debito
    , ie_calcula_amb_sus
    , nr_seq_trans_item_rep
    , ie_valor_mat_estoque
    , ie_info_estab_relat
    , ie_lib_rep_item
    , ie_forma_espec_conta
    , ie_regra_proc_princ
    , ie_grava_evento_autor_conv
    , ie_baixa_unica_ret
    , ie_material_exec_fatur
    , ie_define_ch_crit_hor
    , ie_regra_libera_evolucao
    , ie_lanc_aut_assumir_pac
    , ie_atualiza_guia_eup
    , ie_regra_tx_qtde_exec
    , ie_valor_brasindice
    , ie_validar_log_ligacao
    , ie_atualiza_dt_contab_prot
    , ie_medic_aux_princ_ipe
    , ie_regra_arredondamento_tx
    , ie_agrup_data_ipe_pa
    , ie_despreza_casa_cbhpm
    , nr_seq_trans_item_rep_adic
    , ie_desp_repasse_cartao
    , ie_agrup_data_ipe_exame
    , ie_vincular_rep_proc_pos
    , ie_atualiza_guia_age_cons
    , ie_ch_custo_oper_serv
    , ie_restringe_partic_proc_cir
    , ie_conta_convenio_estab
    , ie_manter_resp_cred
    , ie_gerar_saldo_itens_autor
    , ie_view_honorario
    , ie_justificativa_obs
    , ie_canc_conta_glosa_sus
    , ie_utiliza_video_ipe_internado
    , ie_aplic_perc_autorizado
    , cd_centro_custo_rep_prov
    , cd_conta_cont_rep
    , cd_conta_cont_rep_prov
    , nr_seq_trans_rep_prov
    , ie_excluir_mat_autor
    , ie_gastos_rn_alta
    , ie_consiste_sit_glosa
    , ie_tipo_autor_padrao
    , ie_tipo_guia_padrao
    , ie_vl_cad_glosa_perc_ipe
    , nr_dias_gastos_rn
    , ie_lanc_sus_setor_int
    , ie_contab_desconto_rec
    , ie_gerar_nota_data_ipe_pa
    , ie_gerar_nota_data_ipe_exame
    , ie_recalcular_conta
    , ie_ordem_arred_serv
    , ie_ordem_converte_proc
    , ie_guia_transf_conta
    , ie_prior_edicao_cbhpm
    , cd_classif_setor_rn
    , ie_conta_financ_nf
    , ie_autor_vl_conta
    , ie_vincula_cirur_lanc
    , ie_contab_sus_prefatur
    , ie_atualiza_espec_medica
    , ie_regra_tipo_atend
    , ie_dup_autor_agenda
    , ie_atualiza_kit
    , ie_adic_hor_partic
    , ie_gera_vl_mat_zero_ipe_int
    , ie_estagio_autor
    , ie_vinc_repasse_ret
    , ie_separa_conta_setor
    , ie_espec_taxa_diaria
    , cd_conta_repasse_rec
    , ie_cancela_autor_exec
    , ie_considerar_adic_hora_ipe
    , ie_estagio_autor_transf
    , ie_canc_autor_agenda
    , ie_ordem_alfab_ipe_exames
    , ie_data_adic_hor
    , ie_gerar_pacote_alta
    , ie_gerar_proc_adic_sus
    , ie_transfere_gasto_sus
    , ie_atualizar_dias_autor
    , ie_regra_conta_terc_serv
    , ie_cancelar_autor_alta
    , ie_consid_item_neg_ipe_int
    , ie_tipo_autor_conv_esp
    , ie_aplicar_tx_co_cbhpm
    , ie_conv_autor_exec
    , ie_vincula_cirur_lanc_mat
    , ie_atualiza_autor_vaga
    , ie_data_proc_interno
    , ie_consiste_fpo_execucao
    , ie_data_proc_dias_int
    , ie_pos_item_ipe_exames
    , ie_pos_item_ipe_pa
    , ie_consiste_fpo_prescr
    , ie_valor_inf_partic
    , ie_vincula_cirur_kit_mat
    , ie_estab_regra_crit_hor
    , ie_contab_nf_estorno
    , ie_regra_rn_item
    , cd_conta_contabil_tx_adm
    , ie_atual_autor_troca_conv_ag
    , ie_regra_uso_rla
    , ie_regra_preco_tab_mat
    , ie_aplica_qt_proc_calc
    , ie_nf_conta_canc
    , ie_dia_internacao_rla
    , ie_valor_inf_mat_autor
    , ie_agrup_lote_rec
    , ie_data_proc_comp_preco
    , ie_tipo_setor_classif_rn
    , ie_estagio_parc_autor_agenda
    , ie_calc_adicional_horario
    , ie_cons_qt_proc_autor_cir
    , ie_gerar_autor_guia_prescr
    , ie_tab_preco_mat_interna
    , ie_data_vig_preco_mat_autor
    , ie_preco_cbhpm_data
    , ie_contab_sus_receita
    , ie_aplica_desc_partic
    , ie_gerar_autor_alta_job
    , ie_consiste_moeda
    , ie_resp_cred_glosa_perc
    , ie_troca_conv_partic_kit
    , ie_consid_proc_int_adic
    , ie_valor_simpro
    , cd_convenio_orc
    , cd_categoria_orc
    , cd_plano_orc
    , ie_excluir_rep_desfazer
    , ie_regra_centro_estab
    , ie_estagio_vl_conta_autor
    , ie_atualizar_vigencia_atend
    , ie_contab_rec_proc_aih
    , ie_proc_interno_conv
    , ie_atualiza_guia_prescr
    , ie_log_valor_proc
    , ie_lib_rep_tit_cheque
    , ie_aplica_tx_conv_preco
    , ie_tx_partic_valor_negoc
    , ie_calcular_proc_auditado
    , ie_glosa_proc_zerado_sus
    , ie_ajusta_resp_cred_glosa
    , ie_troca_conv_atend_aih_laudo
    , ie_data_mat_dias_int
    , ie_autor_onc_sem_mat
    , ie_regra_uso_tx_sala
    , ie_consid_item_neg_ipe_exa
    , ie_gerar_vl_cotado_opme_autor
    , ie_data_proc_adic_sus
    , ie_data_exame_lab
    , ie_tributo_pessoa
    , ie_atualiza_unid_consumo
    , ie_agrup_pro_vin_pric_ipe_ex
    , ie_gerar_dados_lote_fornec
    , ie_informa_classif_sus
    , ie_despesa_pre_fatur
    , ie_atualiza_conta_pre
    , ie_desmarca_vl_inf_sus
    , ie_mantem_qtd_proc_sus
    , ie_regra_acresc_mat_autor
    , ie_conv_conta_param_sus
    , ie_exame_lab_conv
    , ie_gerar_rep_conta_prefat
    , ie_lac_proc_conta_apac_bpa
    , ie_ordem_relac_bras
    , ie_estorno_conta_contab_redut
    , ie_prioridade_brasindice
    , ie_regra_restrita_etapa
    , ie_gerar_resp_cred_partic
    , ie_ajusta_val_matmed_ch_ipe
    , ie_ponto_amb
    , ie_autor_mat_prescr_agrup
    , ie_desc_financ_resumo
    , ie_contab_rec_gratuidade
    , ie_consiste_agen_exam
    , cd_clas_setor_rn_sus
    , ie_calc_vlpartic_iamspe
    , ie_atual_pre_fatur_mes
    , ie_data_agenda_rla
    , ie_excluir_proc_repasse
    , ie_exc_matmed_vlzero_ipe_int
    , ie_forma_fechamento
    , ie_canc_autor_agen_cons
    , ie_autor_prorrog_atend
    , ie_fornec_mat_autor_esp
    , ie_forma_cid_princ_ipasgo
    , ie_controla_nota_conta_ipe
    , ie_ratear_rep_pacote
    , ie_mot_alta_conta_ipasgo
    , ie_carater_int_quimio
    , ie_repasse_partic_grg
    , ie_origem_contab_trib_rec
    , ie_fluxo_mmed
    , ie_consiste_ult_edicao_amb
    , ie_ordem_tuss_mat
    , ie_forma_consistir_titulo
    , ie_recalcula_proc_rateio
    , ie_versao_xml_sissa
    , ie_ctb_estab_centro
    , ie_atualiza_qt_dia_solic
    , ie_atualiza_valor_conta
    , to_char(qt_meses_residente) AS qt_meses_residente
    , ie_consiste_periodo_item
    , ie_atual_fim_vigencia_atend
    , ie_log_medico_exec_proc
    , ie_considerar_cns_ant
    , ie_tuss_exam_proc_int
    , ie_regra_ipasgo
    , ie_atual_res_conta_rec_rep
    , ie_regra_exibe_conv
    , ie_agrupa_conta_case
    , ie_prioridade_simpro
    , ie_agrup_data_serv_ipe
    , ie_valor_inf_alt_proc
    , ie_solic_compra_repasse
    , ie_rn_regra_tx_tempo_setor
    , ie_ordem_val_item_ipe
    , ie_log_valor_mat
    , ie_recalcular_pacote
    , ie_show_all_issues_ir
    , ie_valida_pacote_auto_re
    , ie_justificate_by_item
    , ie_consider_cutoff_hour
    , ie_atualiza_rel_cc_pre
    , ie_transf_conta_repasse
    , ie_show_result_ir
    , ie_integra_finnegans
    , cd_proc_integracao
    , ie_origem_proc_int
    , ie_generate_taxes
    , ie_gravar_log
    , ie_diaria_dia_ant
    , ie_reaplic_glosa_item
    , ie_desconto_contabil
    , cd_conta_desconto
    , cd_conta_desconto_pre_fatur 
FROM tasy.parametro_faturamento