SELECT 
	CD_ESTABELECIMENTO
	, CD_LOCAL_ESTOQUE
	, CD_MATERIAL
    , TO_CHAR(DT_MESANO_REFERENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_MESANO_REFERENCIA
    , to_char(QT_ESTOQUE) AS QT_ESTOQUE
    , to_char(VL_ESTOQUE) AS VL_ESTOQUE
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
    , to_char(VL_CUSTO_MEDIO) AS VL_CUSTO_MEDIO
    , to_char(VL_PRECO_ULT_COMPRA) AS VL_PRECO_ULT_COMPRA
    , TO_CHAR(DT_ULT_COMPRA, 'YYYY-MM-DD hh24:mi:ss') AS DT_ULT_COMPRA
    , to_char(QT_CONSUMO) AS QT_CONSUMO
    , to_char(QT_ESTOQUE_MEDIO) AS QT_ESTOQUE_MEDIO
FROM 
	TASY.SALDO_ESTOQUE se 
WHERE
	DT_ATUALIZACAO >= to_date('2019-01-01','yyyy-mm-dd')