SELECT 
	NR_SEQUENCIA
	, CD_SIMPRO
    , TO_CHAR(DT_VIGENCIA, 'YYYY-MM-DD hh24:mi:ss') AS DT_VIGENCIA
    , TO_CHAR(DT_ATUALIZACAO, 'YYYY-MM-DD hh24:mi:ss') AS DT_ATUALIZACAO
	, IE_TIPO_PRECO
    , to_char(VL_PRECO_FABRICA) AS VL_PRECO_FABRICA
    , to_char(VL_PRECO_VENDA) AS VL_PRECO_VENDA
	, IE_TIPO_ALTERACAO
	, IE_TIPO_EMBALAGEM
	, IE_TIPO_FRACAO
    , to_char(QT_EMBALAGEM) AS QT_EMBALAGEM
    , to_char(QT_FRACAO) AS QT_FRACAO
    , to_char(VL_PRECO_FABRICA_FRACAO) AS VL_PRECO_FABRICA_FRACAO
	, CD_FRACAO
	, IE_MERCADO
	, NR_REG_ANVISA
	, DT_VALIDADE
	, IE_RESTRITO
	, IE_FRACIONADO
	, CD_TUSS
	, IE_CLASSIFICACAO
    , NULLIF(REGEXP_REPLACE(DS_REFERENCIA_PRODUTO,'[''"!/:@;]', ''),'') AS DS_REFERENCIA_PRODUTO 
	, IE_GENERICO
	, CD_ESTABELECIMENTO
	, IE_DIVERSOS
    , TO_CHAR(DT_FORA_LINHA_ITEM, 'YYYY-MM-DD hh24:mi:ss') AS DT_FORA_LINHA_ITEM
FROM 
    TASY.SIMPRO_PRECO